# Generated by Django 2.1.7 on 2019-03-01 04:28

from django.db import migrations, models
import sucursales.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('codigo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=10, validators=[sucursales.validators.validateNumber])),
                ('tipo', models.CharField(choices=[('P', 'Principal'), ('G', 'General')], max_length=1)),
            ],
        ),
    ]
