# Generated by Django 2.1.7 on 2019-03-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['codigo'], 'verbose_name': 'sucursal', 'verbose_name_plural': 'sucursales'},
        ),
        migrations.AddField(
            model_name='sucursal',
            name='localidad',
            field=models.CharField(default='Cali', max_length=200),
            preserve_default=False,
        ),
    ]
